### ISSUE TITLE
whether and where this paper is published

### ISSUE THREAD

**Issue by ghost** [tech-srl/bottleneck#1]
Hi, Uri Alon, I love this work. I think your paper is splendid and innovative to follow. And I want to know whether and where this paper is published. I can't wait to cite your paper as my support.

**Comment by urialon** [comment]
Hi @MGwave ,
Thank you so much for your kind words!
I'm glad that you liked it.
The paper is currently still under review, but you can cite the arxiv version:

```
@article{alon2020bottleneck,
  title={On the Bottleneck of Graph Neural Networks and its Practical Implications},
  author={Alon, Uri and Yahav, Eran},
  journal={arXiv preprint arXiv:2006.05205},
  year={2020}
}
```

Best,
Uri

**Comment by ghost** [comment]
Thank you~ Good luck!! : )

**Comment by urialon** [comment]
Hi @MGwave ,
I hope you are well.
If this is still relevant, the paper is going to appear in ICLR'2021.
You can use this bib entry:

```
@inproceedings{
    alon2021on,
    title={On the Bottleneck of Graph Neural Networks and its Practical Implications},
    author={Uri Alon and Eran Yahav},
    booktitle={International Conference on Learning Representations},
    year={2021},
    url={https://openreview.net/forum?id=i80OPhOCVH2}
}
```

Best,
Uri
