### ISSUE TITLE
Do task have the attribute of DICTIONARY

### ISSUE THREAD

**Issue by UnBuen** [tech-srl/bottleneck#4]
![image](https://user-images.githubusercontent.com/37174252/126172937-05ccdd03-1797-47f9-aaaf-50b4f2fda8b0.png)

Dear tech-srl,
maybe hear is a mistake.

**Comment by urialon** [comment]
Hi @UnBuen ,
Thank you for reporting this!

The task should indeed be `NEIGHBORS_MATCH`.
This flag can also be omitted because this task is the default.

I will fix this in the README.

Best,
Uri

**Comment by UnBuen** [comment]
Dear Uri,
Sorry to bother you again~

when I run command `python run-gcn-2-8.py`,
There maybe is a problem with the number of training examples and test examples.
![image](https://user-images.githubusercontent.com/37174252/126326035-9b152683-bcb7-492d-bf9b-b7ae5e670a49.png)

Have you encountered this problem, or do you have any solutions?
Best, Unbuen

**Comment by urialon** [comment]
Hi @UnBuen ,
This is not a bother at all.

With `depth=2`, the number of leaves is 4, so combinatorially there is only a small number of possible different examples.

`depth=2` is really a toy example.

**Comment by UnBuen** [comment]
> Hi @UnBuen ,
> This is not a bother at all.
> 
> With `depth=2`, the number of leaves is 4, so combinatorially there is only a small number of possible different examples.
> 
> `depth=2` is really a toy example.

Hi, Uri,
Oh, I understand now, thanks a lot

**Comment by UnBuen** [comment]
Hi @urialon ,
I ran into another problem when I ran the `tf-gnn-samples/run_qm9_benchs_fa.py` and `tf-gnn-samples/run_varmisuse_benchs_fa.py`

**My development**(cent os 7 and python3.6)
![image](https://user-images.githubusercontent.com/37174252/126423766-d5056686-621f-429c-82e3-a3be5691f779.png)
![image](https://user-images.githubusercontent.com/37174252/126423855-6623c468-04e9-4566-b2b5-eac5642711e6.png)

**Problem description**
![image](https://user-images.githubusercontent.com/37174252/126424111-3174e724-cf7f-4564-b4b2-74ea8b727438.png)
![image](https://user-images.githubusercontent.com/37174252/126424340-8e3aa22f-3292-4086-8bfb-f1278316c476.png)

**If you have encountered this problem**, please help me or give me some suggestions, thanks.
I saw other people also have this problem on github and some blog, but many people do not have a correct solution.

**If you have time**, please give me some suggestions, it's okay if you are busy, I can also consult my seniors and mentors.

Wish you success in your studies and work.
Best, 
UnBuen.

**Comment by urialon** [comment]
Hi UnBuen,
Sorry for the delayed response!

I did encounter this in the past. The `run_qm9_benchs_fa.py` script is originally from Microsoft's `tf-gnn-samples` repo.
It is simply a loop that runs `train.py` 5 times. The problem is that if `train.py` fails, it hides the errors.
One way to see what was the error is to check the directory that you provided to `run_qm9_benchs_fa.py` as the first argument. For example, if you ran:
```
python run_qm9_benchs_fa.py myLogsDir/
```

then check `myLogsDir/` to see if you can identify the error.
If you can't find the error, try running `train.py` using Microsoft's instructions here: [https://github.com/tech-srl/bottleneck/tree/main/tf-gnn-samples#running](https://github.com/tech-srl/bottleneck/tree/main/tf-gnn-samples#running).

Let me know how it goes.
Best,
Uri

**Comment by UnBuen** [comment]
> Hi UnBuen,
> Sorry for the delayed response!
> 
> I did encounter this in the past. The `run_qm9_benchs_fa.py` script is originally from Microsoft's `tf-gnn-samples` repo.
> It is simply a loop that runs `train.py` 5 times. The problem is that if `train.py` fails, it hides the errors.
> One way to see what was the error is to check the directory that you provided to `run_qm9_benchs_fa.py` as the first argument. For example, if you ran:
> 
> ```
> python run_qm9_benchs_fa.py myLogsDir/
> ```
> 
> then check `myLogsDir/` to see if you can identify the error.
> If you can't find the error, try running `train.py` using Microsoft's instructions here: https://github.com/tech-srl/bottleneck/tree/main/tf-gnn-samples#running.
> 
> Let me know how it goes.
> Best,
> Uri

Hi Uri,
Thank you for your valuable comments. I have solved my problem. The reason for the previous failure is due to the dataset and data processing part. I have found a solution from https://github.com/microsoft/tf-gnn-samples,. Thank you again for your patience.
Best,
UnBuen

**Comment by urialon** [comment]
Great, glad to hear!
Let me know if you have any further questions.
