### ISSUE TITLE
about input data

### ISSUE THREAD

**Issue by SteveTanggithub** [tech-srl/bottleneck#5]
i am confused for the input data of GIN model code part:
**x, edge_index, batch = data.x, data.edge_index, data.batch**
could you explain the three ones?

**Comment by urialon** [comment]
Hi @SteveTanggithub ,
Thank you for your interest in our work!

This is actually not specific to GIN, but it is just the way that PyTorch Geometric works:
* `data.x` is a matrix whose rows are node vectors
* `data.edge_index` is a matrix with two rows, where every column describes an edge. The values in each such column are the indices of the source and target nodes for this edge.
* `data.batch` is a vector which maps each node to its respective graph in the batch.

See more details here:
[https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html](https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html)

Best,
Uri
